Remove observable interface
autonomys/auto-sdk pull request #210
Opened 2024-12-20 12:49 UTC by clostao

2024-12-20 16:37 UTC, marc-aurele-besner requested changes
This is great! 💪 
Can we reflect these changes in the package README please?

2024-12-23 12:12 UTC, clostao commented
Updated, thanks!

2024-12-23 12:30 UTC, marc-aurele-besner reviewed
Awesome, just some small miss in most import in the readme, let's try to make these code snippet as copy/pastable as possible without errors 👍

2024-12-23 12:30 UTC, marc-aurele-besner commented on packages/auto-drive/README.md
most import are missing `createAutoDriveApi`

2024-12-23 12:53 UTC, marc-aurele-besner approved these changes
Awesome work, thank you very much 🙇‍♂️

2024-12-23 13:18 UTC, merged